language: node_js
sudo: false

os:
  - linux

node_js:
  - 6.11.0

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run test

after_script:
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
